const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { test } = require('node:test')

const repoRoot = path.resolve(__dirname, '..')

function readRepoFile(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')
}

test('Node runtime version is aligned across package metadata, Docker, CI, and docs', () => {
  const packageJson = JSON.parse(readRepoFile('package.json'))
  const dockerfile = readRepoFile('Dockerfile')
  const workflow = readRepoFile('.github/workflows/docker.yml')
  const contributing = readRepoFile('CONTRIBUTING.md')

  assert.equal(packageJson.engines?.node, '>=24 <25')
  assert.match(dockerfile, /^FROM node:24-slim AS builder$/m)
  assert.match(dockerfile, /^FROM node:24-slim AS runtime$/m)
  assert.match(workflow, /^\s+node-version: 24$/m)
  assert.match(contributing, /- Node\.js 24/)
  assert.doesNotMatch(contributing, /Node\.js 18/)
})

test('npm test remains a contract-test plus Docker-build quality gate', () => {
  const packageJson = JSON.parse(readRepoFile('package.json'))
  const contributing = readRepoFile('CONTRIBUTING.md')

  assert.equal(packageJson.scripts?.['test:contracts'], 'node --test test/*.test.js')
  assert.equal(packageJson.scripts?.test, 'npm run test:contracts && npm run build:docker')
  assert.match(contributing, /contract tests and then the Docker\s+TypeScript build/)
})

test('Docker WebUI split source files are still injected into the served HTML shell', () => {
  const packageJson = JSON.parse(readRepoFile('package.json'))
  const webui = readRepoFile('src/docker/webui.ts')
  const indexHtml = readRepoFile('src/docker/webui/index.html')
  const app = readRepoFile('src/docker/webui/app.js')
  const appData = readRepoFile('src/docker/webui/app-data.js')
  const appRouting = readRepoFile('src/docker/webui/app-routing.js')
  const appDom = readRepoFile('src/docker/webui/app-dom.js')
  const appRender = readRepoFile('src/docker/webui/app-render.js')
  const appPages = readRepoFile('src/docker/webui/app-pages.js')
  const appActions = readRepoFile('src/docker/webui/app-actions.js')
  const appTaskActions = readRepoFile('src/docker/webui/app-task-actions.js')
  const styles = readRepoFile('src/docker/webui/styles.css')
  const componentStyles = readRepoFile('src/docker/webui/styles-components.css')
  const tableStyles = readRepoFile('src/docker/webui/styles-tables.css')
  const responsiveStyles = readRepoFile('src/docker/webui/styles-responsive.css')

  assert.match(packageJson.scripts?.['build:docker'], /cp -R src\/docker\/webui build\/docker\/docker\/webui/)
  assert.match(webui, /WEBUI_TEMPLATE_PATH = path\.join\(__dirname, 'webui', 'index\.html'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'styles\.css'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'styles-components\.css'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'styles-tables\.css'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'styles-responsive\.css'\)/)
  assert.match(webui, /WEBUI_STYLE_PATHS\.map\(readTextFile\)\.join\('\\n'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-data\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-routing\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-dom\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-render\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-pages\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-task-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app\.js'\)/)
  assert.match(webui, /WEBUI_SCRIPT_PATHS\.map\(readTextFile\)\.join\('\\n;\\n'\)/)
  assert.match(webui, /replaceToken\(html, '__WEBUI_STYLES__', readStyles\(\)\)/)
  assert.match(webui, /replaceToken\(html, '__WEBUI_SCRIPT__', readScript\(\)\)/)
  assert.match(webui, /replaceToken\(html, '__DOCKER_WEBUI_PAGE_ROUTES_JSON__', JSON\.stringify\(DOCKER_WEBUI_PAGE_ROUTES\)\)/)

  assert.match(indexHtml, /__WEBUI_STYLES__/)
  assert.match(indexHtml, /__WEBUI_SCRIPT__/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_DATA/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_ROUTING/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_DOM/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_RENDER/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_PAGES/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_ACTIONS/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_TASK_ACTIONS/)
  assert.match(appData, /window\.DOUYU_KEEP_WEBUI_DATA/)
  assert.match(appRouting, /__DOCKER_WEBUI_PAGE_ROUTES_JSON__/)
  assert.match(appRouting, /window\.DOUYU_KEEP_WEBUI_ROUTING/)
  assert.match(appDom, /window\.DOUYU_KEEP_WEBUI_DOM/)
  assert.match(appRender, /window\.DOUYU_KEEP_WEBUI_RENDER/)
  assert.match(appRender, /buildFansStatusTable/)
  assert.match(appPages, /window\.DOUYU_KEEP_WEBUI_PAGES/)
  assert.match(appPages, /renderOverview/)
  assert.match(appActions, /window\.DOUYU_KEEP_WEBUI_ACTIONS/)
  assert.match(appActions, /loadFansStatus/)
  assert.match(appTaskActions, /window\.DOUYU_KEEP_WEBUI_TASK_ACTIONS/)
  assert.match(appTaskActions, /saveDoubleConfig/)
  assert.match(styles, /:root\{/)
  assert.match(componentStyles, /\.grid\{/)
  assert.match(tableStyles, /\.table-shell\{/)
  assert.match(responsiveStyles, /@media \(prefers-reduced-motion: reduce\)/)
})
