const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { test } = require('node:test')

const repoRoot = path.resolve(__dirname, '..')

function readRepoFile(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')
}

test('Node runtime version is aligned across package metadata, Docker, CI, and docs', () => {
  const packageJson = JSON.parse(readRepoFile('package.json'))
  const dockerfile = readRepoFile('Dockerfile')
  const workflow = readRepoFile('.github/workflows/docker.yml')
  const contributing = readRepoFile('CONTRIBUTING.md')

  assert.equal(packageJson.engines?.node, '>=24 <25')
  assert.match(dockerfile, /^FROM node:24-slim AS builder$/m)
  assert.match(dockerfile, /^FROM node:24-slim AS runtime$/m)
  assert.match(workflow, /^\s+node-version: 24$/m)
  assert.match(contributing, /- Node\.js 24/)
  assert.doesNotMatch(contributing, /Node\.js 18/)
})

test('npm test remains a contract-test plus Docker-build quality gate', () => {
  const packageJson = JSON.parse(readRepoFile('package.json'))
  const contributing = readRepoFile('CONTRIBUTING.md')

  assert.equal(packageJson.scripts?.['test:contracts'], 'node --test test/*.test.js')
  assert.equal(packageJson.scripts?.test, 'npm run test:contracts && npm run build:docker')
  assert.match(contributing, /contract tests and then the Docker\s+TypeScript build/)
})

test('Docker WebUI split source files are still injected into the served HTML shell', () => {
  const packageJson = JSON.parse(readRepoFile('package.json'))
  const webui = readRepoFile('src/docker/webui.ts')
  const indexHtml = readRepoFile('src/docker/webui/index.html')
  const app = readRepoFile('src/docker/webui/app.js')
  const appData = readRepoFile('src/docker/webui/app-data.js')
  const appRouting = readRepoFile('src/docker/webui/app-routing.js')
  const appDom = readRepoFile('src/docker/webui/app-dom.js')
  const appState = readRepoFile('src/docker/webui/app-state.js')
  const appManagedData = readRepoFile('src/docker/webui/app-managed-data.js')
  const appProtectedState = readRepoFile('src/docker/webui/app-protected-state.js')
  const appRequest = readRepoFile('src/docker/webui/app-request.js')
  const appTableRender = readRepoFile('src/docker/webui/app-table-render.js')
  const appRender = readRepoFile('src/docker/webui/app-render.js')
  const appPageCron = readRepoFile('src/docker/webui/app-page-cron.js')
  const appDoubleTaskPage = readRepoFile('src/docker/webui/app-double-task-page.js')
  const appTaskPages = readRepoFile('src/docker/webui/app-task-pages.js')
  const appPages = readRepoFile('src/docker/webui/app-pages.js')
  const appCookieActions = readRepoFile('src/docker/webui/app-cookie-actions.js')
  const appSystemResourceActions = readRepoFile('src/docker/webui/app-system-resource-actions.js')
  const appFansResourceActions = readRepoFile('src/docker/webui/app-fans-resource-actions.js')
  const appYubaResourceActions = readRepoFile('src/docker/webui/app-yuba-resource-actions.js')
  const appResourceActions = readRepoFile('src/docker/webui/app-resource-actions.js')
  const appAuthActions = readRepoFile('src/docker/webui/app-auth-actions.js')
  const appActions = readRepoFile('src/docker/webui/app-actions.js')
  const appSimpleTaskActions = readRepoFile('src/docker/webui/app-simple-task-actions.js')
  const appSendTaskActions = readRepoFile('src/docker/webui/app-send-task-actions.js')
  const appTaskActions = readRepoFile('src/docker/webui/app-task-actions.js')
  const appEvents = readRepoFile('src/docker/webui/app-events.js')
  const styles = readRepoFile('src/docker/webui/styles.css')
  const componentStyles = readRepoFile('src/docker/webui/styles-components.css')
  const tableStyles = readRepoFile('src/docker/webui/styles-tables.css')
  const responsiveStyles = readRepoFile('src/docker/webui/styles-responsive.css')

  assert.match(packageJson.scripts?.['build:docker'], /cp -R src\/docker\/webui build\/docker\/docker\/webui/)
  assert.match(webui, /WEBUI_TEMPLATE_PATH = path\.join\(__dirname, 'webui', 'index\.html'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'styles\.css'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'styles-components\.css'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'styles-tables\.css'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'styles-responsive\.css'\)/)
  assert.match(webui, /WEBUI_STYLE_PATHS\.map\(readTextFile\)\.join\('\\n'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-data\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-routing\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-dom\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-state\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-managed-data\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-protected-state\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-request\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-table-render\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-render\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-page-cron\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-double-task-page\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-task-pages\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-pages\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-cookie-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-system-resource-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-fans-resource-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-yuba-resource-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-resource-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-auth-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-simple-task-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-send-task-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-task-actions\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app-events\.js'\)/)
  assert.match(webui, /path\.join\(__dirname, 'webui', 'app\.js'\)/)
  assert.match(webui, /WEBUI_SCRIPT_PATHS\.map\(readTextFile\)\.join\('\\n;\\n'\)/)
  assert.match(webui, /replaceToken\(html, '__WEBUI_STYLES__', readStyles\(\)\)/)
  assert.match(webui, /replaceToken\(html, '__WEBUI_SCRIPT__', readScript\(\)\)/)
  assert.match(webui, /replaceToken\(html, '__DOCKER_WEBUI_PAGE_ROUTES_JSON__', JSON\.stringify\(DOCKER_WEBUI_PAGE_ROUTES\)\)/)

  assert.match(indexHtml, /__WEBUI_STYLES__/)
  assert.match(indexHtml, /__WEBUI_SCRIPT__/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_DATA/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_ROUTING/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_DOM/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_RENDER/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_PAGES/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_ACTIONS/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_TASK_ACTIONS/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_EVENTS/)
  assert.match(appData, /window\.DOUYU_KEEP_WEBUI_DATA/)
  assert.match(appRouting, /__DOCKER_WEBUI_PAGE_ROUTES_JSON__/)
  assert.match(appRouting, /window\.DOUYU_KEEP_WEBUI_ROUTING/)
  assert.match(appDom, /window\.DOUYU_KEEP_WEBUI_DOM/)
  assert.match(appState, /window\.DOUYU_KEEP_WEBUI_STATE/)
  assert.match(appManagedData, /window\.DOUYU_KEEP_WEBUI_MANAGED_DATA/)
  assert.match(appManagedData, /applyFansStatusBase/)
  assert.match(appProtectedState, /window\.DOUYU_KEEP_WEBUI_PROTECTED_STATE/)
  assert.match(appProtectedState, /clearProtectedState/)
  assert.match(appRequest, /window\.DOUYU_KEEP_WEBUI_REQUEST/)
  assert.match(appRequest, /requestJson/)
  assert.match(appTableRender, /window\.DOUYU_KEEP_WEBUI_TABLE_RENDER/)
  assert.match(appTableRender, /buildSendTable/)
  assert.match(appRender, /window\.DOUYU_KEEP_WEBUI_RENDER/)
  assert.match(appRender, /DOUYU_KEEP_WEBUI_TABLE_RENDER/)
  assert.match(appPageCron, /window\.DOUYU_KEEP_WEBUI_PAGE_CRON/)
  assert.match(appPageCron, /loadCronPreview/)
  assert.match(appDoubleTaskPage, /window\.DOUYU_KEEP_WEBUI_DOUBLE_TASK_PAGE/)
  assert.match(appDoubleTaskPage, /updateDoubleModeUi/)
  assert.match(appTaskPages, /window\.DOUYU_KEEP_WEBUI_TASK_PAGES/)
  assert.match(appTaskPages, /renderDoublePage/)
  assert.match(appPages, /window\.DOUYU_KEEP_WEBUI_PAGES/)
  assert.match(appPages, /renderOverview/)
  assert.match(appCookieActions, /window\.DOUYU_KEEP_WEBUI_COOKIE_ACTIONS/)
  assert.match(appSystemResourceActions, /window\.DOUYU_KEEP_WEBUI_SYSTEM_RESOURCE_ACTIONS/)
  assert.match(appSystemResourceActions, /loadOverview/)
  assert.match(appFansResourceActions, /window\.DOUYU_KEEP_WEBUI_FANS_RESOURCE_ACTIONS/)
  assert.match(appFansResourceActions, /loadFansStatus/)
  assert.match(appYubaResourceActions, /window\.DOUYU_KEEP_WEBUI_YUBA_RESOURCE_ACTIONS/)
  assert.match(appYubaResourceActions, /loadYubaStatus/)
  assert.match(appResourceActions, /window\.DOUYU_KEEP_WEBUI_RESOURCE_ACTIONS/)
  assert.match(appResourceActions, /DOUYU_KEEP_WEBUI_FANS_RESOURCE_ACTIONS/)
  assert.match(appAuthActions, /window\.DOUYU_KEEP_WEBUI_AUTH_ACTIONS/)
  assert.match(appAuthActions, /loginWithPassword/)
  assert.match(appActions, /window\.DOUYU_KEEP_WEBUI_ACTIONS/)
  assert.match(appActions, /loadProtectedData/)
  assert.match(appSimpleTaskActions, /window\.DOUYU_KEEP_WEBUI_SIMPLE_TASK_ACTIONS/)
  assert.match(appSimpleTaskActions, /saveYubaConfig/)
  assert.match(appSendTaskActions, /window\.DOUYU_KEEP_WEBUI_SEND_TASK_ACTIONS/)
  assert.match(appSendTaskActions, /saveDoubleConfig/)
  assert.match(appTaskActions, /window\.DOUYU_KEEP_WEBUI_TASK_ACTIONS/)
  assert.match(appTaskActions, /DOUYU_KEEP_WEBUI_SEND_TASK_ACTIONS/)
  assert.match(appEvents, /window\.DOUYU_KEEP_WEBUI_EVENTS/)
  assert.match(appEvents, /createEventBindings/)
  assert.match(styles, /:root\{/)
  assert.match(componentStyles, /\.grid\{/)
  assert.match(tableStyles, /\.table-shell\{/)
  assert.match(responsiveStyles, /@media \(prefers-reduced-motion: reduce\)/)
})
