const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { test } = require('node:test')

const repoRoot = path.resolve(__dirname, '..')

function readRepoFile(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')
}

test('Node runtime version is aligned across package metadata, Docker, CI, and docs', () => {
  const packageJson = JSON.parse(readRepoFile('package.json'))
  const dockerfile = readRepoFile('Dockerfile')
  const workflow = readRepoFile('.github/workflows/docker.yml')
  const contributing = readRepoFile('CONTRIBUTING.md')

  assert.equal(packageJson.engines?.node, '>=24 <25')
  assert.match(dockerfile, /^FROM node:24-slim AS builder$/m)
  assert.match(dockerfile, /^FROM node:24-slim AS runtime$/m)
  assert.match(workflow, /^\s+node-version: 24$/m)
  assert.match(contributing, /- Node\.js 24/)
  assert.doesNotMatch(contributing, /Node\.js 18/)
})

test('npm test remains a contract-test plus Docker-build quality gate', () => {
  const packageJson = JSON.parse(readRepoFile('package.json'))
  const contributing = readRepoFile('CONTRIBUTING.md')

  assert.equal(packageJson.scripts?.['test:contracts'], 'node --test test/*.test.js')
  assert.equal(packageJson.scripts?.test, 'npm run test:contracts && npm run build:docker')
  assert.match(contributing, /contract tests and then the Docker\s+build/)
})

test('Docker WebUI is built by Vite and served as static Docker assets', () => {
  const packageJson = JSON.parse(readRepoFile('package.json'))
  const viteConfig = readRepoFile('vite.config.ts')
  const webui = readRepoFile('src/docker/webui.ts')
  const webuiRoutes = readRepoFile('src/docker/server-webui-routes.ts')
  const viteIndex = readRepoFile('src/docker/webui-src/index.html')
  const main = readRepoFile('src/docker/webui-src/main.ts')
  const appVue = readRepoFile('src/docker/webui-src/App.vue')
  const auth = readRepoFile('src/docker/webui-src/auth.ts')
  const navigation = readRepoFile('src/docker/webui-src/navigation.ts')
  const request = readRepoFile('src/docker/webui-src/request.ts')
  const resources = readRepoFile('src/docker/webui-src/resources.ts')
  const overview = readRepoFile('src/docker/webui-src/overview.ts')
  const collect = readRepoFile('src/docker/webui-src/collect.ts')
  const keepalive = readRepoFile('src/docker/webui-src/keepalive.ts')
  const double = readRepoFile('src/docker/webui-src/double.ts')
  const expiring = readRepoFile('src/docker/webui-src/expiring.ts')
  const cookie = readRepoFile('src/docker/webui-src/cookie.ts')
  const yuba = readRepoFile('src/docker/webui-src/yuba.ts')
  const theme = readRepoFile('src/docker/webui-src/theme.ts')
  const toast = readRepoFile('src/docker/webui-src/toast.ts')
  const legacyCore = readRepoFile('src/docker/webui-src/legacy-core.ts')
  const app = readRepoFile('src/docker/webui/app.js')
  const appState = readRepoFile('src/docker/webui/app-state.js')
  const appManagedData = readRepoFile('src/docker/webui/app-managed-data.js')
  const appProtectedState = readRepoFile('src/docker/webui/app-protected-state.js')
  const appTaskPages = readRepoFile('src/docker/webui/app-task-pages.js')
  const appPages = readRepoFile('src/docker/webui/app-pages.js')
  const appResourceActions = readRepoFile('src/docker/webui/app-resource-actions.js')
  const appActions = readRepoFile('src/docker/webui/app-actions.js')
  const appSimpleTaskActions = readRepoFile('src/docker/webui/app-simple-task-actions.js')
  const appSendTaskActions = readRepoFile('src/docker/webui/app-send-task-actions.js')
  const appTaskActions = readRepoFile('src/docker/webui/app-task-actions.js')
  const appEvents = readRepoFile('src/docker/webui/app-events.js')
  const styles = readRepoFile('src/docker/webui/styles.css')
  const componentStyles = readRepoFile('src/docker/webui/styles-components.css')
  const tableStyles = readRepoFile('src/docker/webui/styles-tables.css')
  const responsiveStyles = readRepoFile('src/docker/webui/styles-responsive.css')

  assert.equal(packageJson.scripts?.['build:webui'], 'npm run type-check:webui && vite build')
  assert.equal(packageJson.scripts?.['type-check:webui'], 'vue-tsc -p tsconfig.webui.json --noEmit')
  assert.match(packageJson.scripts?.['build:docker'], /npm run build:webui/)
  assert.doesNotMatch(packageJson.scripts?.['build:docker'], /cp -R src\/docker\/webui/)
  assert.equal(packageJson.dependencies?.vue, undefined)
  assert.match(packageJson.devDependencies?.vue, /^\^3\./)
  assert.match(packageJson.devDependencies?.vite, /^\^/)
  assert.match(packageJson.devDependencies?.['@vitejs/plugin-vue'], /^\^/)

  assert.match(viteConfig, /@vitejs\/plugin-vue/)
  assert.match(viteConfig, /outDir: '\.\.\/\.\.\/\.\.\/build\/docker\/docker\/webui'/)
  assert.match(viteConfig, /input: 'index\.html'/)
  assert.match(viteConfig, /root: 'src\/docker\/webui-src'/)
  assert.match(webui, /WEBUI_ASSET_ROOT = path\.join\(__dirname, 'webui'\)/)
  assert.match(webui, /WEBUI_TEMPLATE_PATH = path\.join\(WEBUI_ASSET_ROOT, 'index\.html'\)/)
  assert.match(webui, /replaceToken\(html, '__DOCKER_WEBUI_PAGE_ROUTES_JSON__', JSON\.stringify\(DOCKER_WEBUI_PAGE_ROUTES\)\)/)
  assert.match(webuiRoutes, /express\.static\(WEBUI_ASSET_ROOT/)

  assert.match(viteIndex, /<div id="app"><\/div>/)
  assert.match(viteIndex, /DOUYU_KEEP_WEBUI_BOOTSTRAP/)
  assert.match(viteIndex, /__DOCKER_WEBUI_PAGE_ROUTES_JSON__/)
  assert.match(viteIndex, /src="\/main\.ts"/)
  assert.match(appVue, /<script setup lang="ts">/)
  assert.match(appVue, /\{\{ bootstrap\.appName \}\}/)
  assert.match(appVue, /\{\{ bootstrap\.appVersionLabel \}\}/)
  assert.match(appVue, /usePageNavigation\(bootstrap\.pageRoutes\)/)
  assert.match(appVue, /useAuthSession\(\)/)
  assert.match(appVue, /v-show="!authenticated"/)
  assert.match(appVue, /v-show="authenticated"/)
  assert.match(appVue, /@submit\.prevent="submitLogin"/)
  assert.match(appVue, /v-model="password"/)
  assert.match(appVue, /@click="logout"/)
  assert.doesNotMatch(appVue, /data-action="logout"/)
  assert.doesNotMatch(appVue, /id="app-shell" style="display:none"/)
  assert.match(appVue, /useThemeMode\(\)/)
  assert.match(appVue, /useToastRegion\(\)/)
  assert.match(appVue, /useOverviewPage\(\)/)
  assert.match(appVue, /useLogsPage\(activeTab, authenticated\)/)
  assert.match(appVue, /useCollectTaskPage\(\)/)
  assert.match(appVue, /useKeepaliveTaskPage\(\)/)
  assert.match(appVue, /useExpiringGiftTaskPage\(\)/)
  assert.match(appVue, /useYubaTaskPage\(\)/)
  assert.match(appVue, /useCookieLoginPage\(\)/)
  assert.match(appVue, /id="toast-live" role="status" aria-live="polite"/)
  assert.match(appVue, /\{\{ toastLiveMessage \}\}/)
  assert.match(appVue, /\{\{ logsSummary \}\}/)
  assert.match(appVue, /v-model="logsAutoRefresh"/)
  assert.match(appVue, /@click="refreshLogs"/)
  assert.match(appVue, /@click="clearLogs"/)
  assert.match(appVue, /@click="refreshOverview"/)
  assert.match(appVue, /v-for="cell in overviewStatusCells"/)
  assert.match(appVue, /v-for="metric in overviewGiftMetrics"/)
  assert.match(appVue, /\{\{ overviewFansNote \}\}/)
  assert.match(appVue, /v-if="showOverviewLoginAction"/)
  assert.match(appVue, /@click="selectTab\('login'\)"/)
  assert.match(appVue, /v-else-if="showOverviewFansTable"/)
  assert.match(appVue, /v-for="row in overviewFansRows"/)
  assert.doesNotMatch(appVue, /data-action="refresh-overview"/)
  assert.doesNotMatch(appVue, /id="overview-basic-summary"/)
  assert.doesNotMatch(appVue, /id="overview-gift-summary"/)
  assert.doesNotMatch(appVue, /id="overview-fans-note"/)
  assert.doesNotMatch(appVue, /id="overview-fans-table-wrap"/)
  assert.match(appVue, /v-model="mainCookie"/)
  assert.match(appVue, /v-model="yubaCookie"/)
  assert.match(appVue, /v-model="cookieCloud\.active"/)
  assert.match(appVue, /@click="saveCookie"/)
  assert.match(appVue, /@click="saveAndEnableCookieCloud"/)
  assert.match(appVue, /@click="checkCookieSource\(\)"/)
  assert.match(appVue, /v-model="collectEnabled"/)
  assert.match(appVue, /v-model="collectCron"/)
  assert.match(appVue, /@click="saveCollectConfig\(\)"/)
  assert.match(appVue, /@click="triggerCollectTask"/)
  assert.match(appVue, /v-model="yubaEnabled"/)
  assert.match(appVue, /v-model="yubaCron"/)
  assert.match(appVue, /v-model="yubaMode"/)
  assert.match(appVue, /@click="saveYubaConfig\(\)"/)
  assert.match(appVue, /@click="triggerYubaTask"/)
  assert.match(appVue, /v-model="keepaliveEnabled"/)
  assert.match(appVue, /v-model="keepaliveCron"/)
  assert.match(appVue, /v-model\.number="keepaliveModel"/)
  assert.match(appVue, /@click="saveKeepaliveConfig\(\)"/)
  assert.match(appVue, /@click="triggerKeepaliveTask"/)
  assert.match(appVue, /v-model="doubleEnabled"/)
  assert.match(appVue, /v-model="doubleCron"/)
  assert.match(appVue, /v-model="doubleGiftScope"/)
  assert.match(appVue, /v-model\.number="doubleModel"/)
  assert.match(appVue, /v-model="row\.enabled"/)
  assert.match(appVue, /v-model\.number="row\.value"/)
  assert.match(appVue, /@click="saveDoubleConfig\(\)"/)
  assert.match(appVue, /@click="triggerDoubleTask"/)
  assert.match(appVue, /@click="applyDoubleRatioPreset\('equal'\)"/)
  assert.match(appVue, /@click="applyDoubleRatioPreset\('level'\)"/)
  assert.match(appVue, /v-model="expiringEnabled"/)
  assert.match(appVue, /v-model="expiringCron"/)
  assert.match(appVue, /v-model\.number="expiringThresholdHours"/)
  assert.match(appVue, /v-model\.number="expiringModel"/)
  assert.match(appVue, /@click="saveExpiringGiftConfig\(\)"/)
  assert.match(appVue, /@click="triggerExpiringTask"/)
  assert.doesNotMatch(appVue, /data-action="refresh-logs"/)
  assert.doesNotMatch(appVue, /data-action="clear-logs"/)
  assert.doesNotMatch(appVue, /data-action="save-cookie"/)
  assert.doesNotMatch(appVue, /data-action="save-cookie-cloud"/)
  assert.doesNotMatch(appVue, /data-action="check-cookie-source"/)
  assert.doesNotMatch(appVue, /data-action="save-collect"/)
  assert.doesNotMatch(appVue, /data-trigger="collectGift"/)
  assert.doesNotMatch(appVue, /data-action="save-yuba"/)
  assert.doesNotMatch(appVue, /data-trigger="yubaCheckIn"/)
  assert.doesNotMatch(appVue, /data-action="save-keepalive"/)
  assert.doesNotMatch(appVue, /data-trigger="keepalive"/)
  assert.doesNotMatch(appVue, /data-action="save-double"/)
  assert.doesNotMatch(appVue, /data-trigger="doubleCard"/)
  assert.doesNotMatch(appVue, /data-action="double-fill-equal"/)
  assert.doesNotMatch(appVue, /data-action="double-fill-level"/)
  assert.doesNotMatch(appVue, /data-action="save-expiring"/)
  assert.doesNotMatch(appVue, /data-trigger="expiringGift"/)
  assert.match(appVue, /v-for="tab in tabs"/)
  assert.match(appVue, /v-for="option in themeModes"/)
  assert.match(appVue, /@click="selectThemeMode\(option\.mode\)"/)
  assert.match(auth, /export function useAuthSession/)
  assert.match(auth, /from '\.\/request'/)
  assert.match(auth, /douyu-keep-webui:auth-state/)
  assert.match(auth, /douyu-keep-webui:legacy-ready/)
  assert.match(auth, /UNAUTHORIZED_EVENT_NAME/)
  assert.match(auth, /\/api\/auth\/status/)
  assert.match(auth, /\/api\/auth\/login/)
  assert.match(auth, /\/api\/auth\/logout/)
  assert.match(auth, /onUnauthorized: false/)
  assert.match(auth, /web-password/)
  assert.match(auth, /window\.history\.replaceState/)
  assert.match(auth, /document\.body\.setAttribute\('data-auth'/)
  assert.match(auth, /showToast\('登录成功', true\)/)
  assert.match(navigation, /export function usePageNavigation/)
  assert.match(navigation, /douyu-keep-webui:navigation/)
  assert.match(navigation, /getAttribute\('data-action'\) === 'tab'/)
  assert.match(theme, /export function useThemeMode/)
  assert.match(theme, /from '\.\/request'/)
  assert.match(theme, /douyu-keep-webui:config/)
  assert.match(theme, /body: JSON\.stringify\(\{ ui: \{ themeMode: nextThemeMode \} \}\)/)
  assert.match(theme, /errorToast: message => `保存主题失败：\$\{message\}`/)
  assert.match(theme, /document\.body\.setAttribute\('data-theme', resolvedTheme\.value\)/)
  assert.match(theme, /theme-color-meta/)
  assert.match(theme, /prefers-color-scheme: dark/)
  assert.match(toast, /export function useToastRegion/)
  assert.match(toast, /douyu-keep-webui:toast/)
  assert.match(toast, /toastLiveMessage/)
  assert.doesNotMatch(theme, /getElementById\('toast/)
  assert.doesNotMatch(theme, /__toastTimer/)
  assert.match(request, /export async function requestJson/)
  assert.match(request, /export function installLegacyRequestBridge/)
  assert.match(request, /douyu-keep-webui:unauthorized/)
  assert.match(request, /showToast\(message, false\)/)
  assert.match(request, /window\.DOUYU_KEEP_WEBUI_REQUEST/)
  assert.match(resources, /export function installLegacySystemResourceBridge/)
  assert.match(resources, /export function installLegacyFansResourceBridge/)
  assert.match(resources, /export function useLogsPage/)
  assert.match(resources, /window\.DOUYU_KEEP_WEBUI_SYSTEM_RESOURCE_ACTIONS/)
  assert.match(resources, /window\.DOUYU_KEEP_WEBUI_FANS_RESOURCE_ACTIONS/)
  assert.match(resources, /createReadOnlyResource/)
  assert.match(resources, /function syncFans/)
  assert.match(resources, /function loadFansList/)
  assert.match(resources, /function loadFansStatus/)
  assert.match(resources, /\/api\/config\/raw/)
  assert.match(resources, /\/api\/overview/)
  assert.match(resources, /\/api\/logs/)
  assert.match(resources, /\/api\/fans\/reconcile/)
  assert.match(resources, /\/api\/fans\/status\/base/)
  assert.match(resources, /\/api\/fans\/status\/details/)
  assert.match(resources, /douyu-keep-webui:config/)
  assert.match(resources, /douyu-keep-webui:overview/)
  assert.match(resources, /加载配置失败/)
  assert.match(resources, /加载概览失败/)
  assert.match(resources, /加载日志失败/)
  assert.match(resources, /method: 'DELETE'/)
  assert.match(resources, /日志已清空/)
  assert.match(resources, /window\.setInterval/)
  assert.match(overview, /export function useOverviewPage/)
  assert.match(overview, /douyu-keep-webui:overview-page/)
  assert.match(overview, /douyu-keep-webui:refresh-state/)
  assert.match(overview, /douyu-keep-webui:refresh-overview-request/)
  assert.match(overview, /formatDate/)
  assert.match(overview, /showOverviewLoginAction/)
  assert.match(overview, /showOverviewFansTable/)
  assert.match(cookie, /export function useCookieLoginPage/)
  assert.match(cookie, /export function installLegacyCookieActionBridge/)
  assert.match(cookie, /window\.DOUYU_KEEP_WEBUI_COOKIE_ACTIONS/)
  assert.match(cookie, /douyu-keep-webui:login-page/)
  assert.match(cookie, /\/api\/config/)
  assert.match(cookie, /\/api\/cookie-source\/persist/)
  assert.match(cookie, /\/api\/cookie-source\/check/)
  assert.match(cookie, /\/api\/cron-preview/)
  assert.match(cookie, /手填 Cookie 已保存/)
  assert.match(cookie, /CookieCloud 已保存并启用/)
  assert.match(collect, /export function useCollectTaskPage/)
  assert.match(collect, /export function installLegacyCollectTaskBridge/)
  assert.match(collect, /window\.DOUYU_KEEP_WEBUI_COLLECT_TASK_ACTIONS/)
  assert.match(collect, /douyu-keep-webui:collect-page/)
  assert.match(collect, /\/api\/config/)
  assert.match(collect, /\/api\/trigger\/collectGift/)
  assert.match(collect, /\/api\/cron-preview/)
  assert.match(collect, /领取任务已保存并启用/)
  assert.match(keepalive, /export function useKeepaliveTaskPage/)
  assert.match(keepalive, /export function installLegacyKeepaliveTaskBridge/)
  assert.match(keepalive, /window\.DOUYU_KEEP_WEBUI_KEEPALIVE_TASK_ACTIONS/)
  assert.match(keepalive, /douyu-keep-webui:keepalive-page/)
  assert.match(keepalive, /\/api\/config/)
  assert.match(keepalive, /\/api\/trigger\/keepalive/)
  assert.match(keepalive, /\/api\/cron-preview/)
  assert.match(keepalive, /保活任务已保存并启用/)
  assert.match(double, /export function useDoubleTaskPage/)
  assert.match(double, /export function installLegacyDoubleTaskBridge/)
  assert.match(double, /window\.DOUYU_KEEP_WEBUI_DOUBLE_TASK_ACTIONS/)
  assert.match(double, /douyu-keep-webui:double-page/)
  assert.match(double, /\/api\/config/)
  assert.match(double, /\/api\/trigger\/doubleCard/)
  assert.match(double, /\/api\/cron-preview/)
  assert.match(double, /双倍任务已保存并启用/)
  assert.match(double, /按权重模式至少需要一个已勾选房间填写大于 0 的权重值/)
  assert.match(expiring, /export function useExpiringGiftTaskPage/)
  assert.match(expiring, /export function installLegacyExpiringTaskBridge/)
  assert.match(expiring, /window\.DOUYU_KEEP_WEBUI_EXPIRING_TASK_ACTIONS/)
  assert.match(expiring, /douyu-keep-webui:expiring-page/)
  assert.match(expiring, /\/api\/config/)
  assert.match(expiring, /\/api\/trigger\/expiringGift/)
  assert.match(expiring, /\/api\/cron-preview/)
  assert.match(expiring, /临期任务已保存并启用/)
  assert.match(yuba, /export function useYubaTaskPage/)
  assert.match(yuba, /export function installLegacyYubaBridge/)
  assert.match(yuba, /window\.DOUYU_KEEP_WEBUI_YUBA_RESOURCE_ACTIONS/)
  assert.match(yuba, /window\.DOUYU_KEEP_WEBUI_YUBA_TASK_ACTIONS/)
  assert.match(yuba, /douyu-keep-webui:yuba-page/)
  assert.match(yuba, /\/api\/config/)
  assert.match(yuba, /\/api\/trigger\/yubaCheckIn/)
  assert.match(yuba, /\/api\/yuba\/status/)
  assert.match(yuba, /\/api\/cron-preview/)
  assert.match(yuba, /鱼吧签到任务已保存并启用/)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-request.js')), false)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-system-resource-actions.js')), false)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-fans-resource-actions.js')), false)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-cookie-actions.js')), false)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-yuba-resource-actions.js')), false)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-double-task-page.js')), false)
  assert.match(main, /createApp\(App\)\.mount\('#app'\)/)
  assert.match(main, /installLegacyCoreBridge\(\)/)
  assert.match(main, /installLegacyRequestBridge\(\)/)
  assert.match(main, /installLegacyCookieActionBridge\(\)/)
  assert.match(main, /installLegacyCollectTaskBridge\(\)/)
  assert.match(main, /installLegacyKeepaliveTaskBridge\(\)/)
  assert.match(main, /installLegacyDoubleTaskBridge\(\)/)
  assert.match(main, /installLegacyExpiringTaskBridge\(\)/)
  assert.match(main, /installLegacyFansResourceBridge\(\)/)
  assert.match(main, /installLegacyYubaBridge\(\)/)
  assert.match(main, /installLegacySystemResourceBridge\(\)/)
  assert.match(main, /import '\.\.\/webui\/styles\.css'/)
  assert.match(main, /import '\.\.\/webui\/styles-components\.css'/)
  assert.match(main, /import '\.\.\/webui\/styles-tables\.css'/)
  assert.match(main, /import '\.\.\/webui\/styles-responsive\.css'/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-data\.js'\)/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-routing\.js'\)/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-dom\.js'\)/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-request\.js'\)/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-system-resource-actions\.js'\)/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-fans-resource-actions\.js'\)/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-cookie-actions\.js'\)/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-yuba-resource-actions\.js'\)/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-double-task-page\.js'\)/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-table-render\.js'\)/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-render\.js'\)/)
  assert.doesNotMatch(main, /await import\('\.\.\/webui\/app-page-cron\.js'\)/)
  assert.match(main, /await import\('\.\.\/webui\/app-events\.js'\)/)
  assert.match(main, /await import\('\.\.\/webui\/app\.js'\)/)
  assert.doesNotMatch(main, /app-auth-actions\.js/)

  assert.match(app, /window\.DOUYU_KEEP_WEBUI_DATA/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_ROUTING/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_DOM/)
  assert.doesNotMatch(app, /window\.DOUYU_KEEP_WEBUI_RENDER/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_PAGES/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_ACTIONS/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_TASK_ACTIONS/)
  assert.match(app, /window\.DOUYU_KEEP_WEBUI_EVENTS/)
  assert.match(app, /DOUYU_KEEP_WEBUI_LEGACY/)
  assert.match(app, /douyu-keep-webui:auth-state/)
  assert.match(app, /douyu-keep-webui:legacy-ready/)
  assert.doesNotMatch(app, /querySelectorAll\('\.tab-btn'\)/)
  assert.doesNotMatch(app, /byId\('auth-shell'\)/)
  assert.doesNotMatch(app, /byId\('login-error'\)/)
  assert.doesNotMatch(app, /byId\('login-submit'\)/)
  assert.doesNotMatch(app, /byId\('page-title'\)\.textContent/)
  assert.match(app, /douyu-keep-webui:unauthorized/)
  assert.match(legacyCore, /export function installLegacyCoreBridge/)
  assert.match(legacyCore, /window\.DOUYU_KEEP_WEBUI_DATA/)
  assert.match(legacyCore, /window\.DOUYU_KEEP_WEBUI_ROUTING/)
  assert.match(legacyCore, /window\.DOUYU_KEEP_WEBUI_DOM/)
  assert.match(legacyCore, /DOUYU_KEEP_WEBUI_BOOTSTRAP/)
  assert.match(legacyCore, /showToast\(String\(message\), Boolean\(ok\)\)/)
  assert.doesNotMatch(legacyCore, /byId\('toast'\)/)
  assert.doesNotMatch(legacyCore, /byId\('toast-live'\)/)
  assert.doesNotMatch(legacyCore, /__toastTimer/)
  assert.doesNotMatch(legacyCore, /querySelectorAll\('\.theme-option/)
  assert.match(appState, /window\.DOUYU_KEEP_WEBUI_STATE/)
  assert.match(appState, /window\.DOUYU_KEEP_WEBUI_DOM\.formatDate/)
  assert.match(appManagedData, /window\.DOUYU_KEEP_WEBUI_MANAGED_DATA/)
  assert.match(appManagedData, /applyFansStatusBase/)
  assert.match(appProtectedState, /window\.DOUYU_KEEP_WEBUI_PROTECTED_STATE/)
  assert.match(appProtectedState, /clearProtectedState/)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-table-render.js')), false)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-render.js')), false)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-page-cron.js')), false)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-data.js')), false)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-routing.js')), false)
  assert.equal(fs.existsSync(path.join(repoRoot, 'src/docker/webui/app-dom.js')), false)
  assert.match(appTaskPages, /window\.DOUYU_KEEP_WEBUI_TASK_PAGES/)
  assert.match(appTaskPages, /renderDoublePage/)
  assert.match(appTaskPages, /douyu-keep-webui:collect-page/)
  assert.match(appTaskPages, /douyu-keep-webui:yuba-page/)
  assert.match(appTaskPages, /douyu-keep-webui:keepalive-page/)
  assert.match(appTaskPages, /douyu-keep-webui:double-page/)
  assert.match(appTaskPages, /douyu-keep-webui:expiring-page/)
  assert.doesNotMatch(appTaskPages, /byId\('collect-task-card'\)\.innerHTML/)
  assert.doesNotMatch(appTaskPages, /byId\('collect-enable'\)\.checked/)
  assert.doesNotMatch(appTaskPages, /byId\('collect-cron'\)\.value/)
  assert.doesNotMatch(appTaskPages, /byId\('yuba-task-card'\)\.innerHTML/)
  assert.doesNotMatch(appTaskPages, /byId\('yuba-enable'\)\.checked/)
  assert.doesNotMatch(appTaskPages, /byId\('yuba-cron'\)\.value/)
  assert.doesNotMatch(appTaskPages, /byId\('yuba-table-wrap'\)\.innerHTML/)
  assert.doesNotMatch(appTaskPages, /byId\('keepalive-task-card'\)\.innerHTML/)
  assert.doesNotMatch(appTaskPages, /byId\('keepalive-enable'\)\.checked/)
  assert.doesNotMatch(appTaskPages, /byId\('keepalive-cron'\)\.value/)
  assert.doesNotMatch(appTaskPages, /byId\('keepalive-table-wrap'\)\.innerHTML/)
  assert.doesNotMatch(appTaskPages, /byId\('double-task-card'\)\.innerHTML/)
  assert.doesNotMatch(appTaskPages, /byId\('double-enable'\)\.checked/)
  assert.doesNotMatch(appTaskPages, /byId\('double-cron'\)\.value/)
  assert.doesNotMatch(appTaskPages, /byId\('double-table-wrap'\)\.innerHTML/)
  assert.doesNotMatch(appTaskPages, /byId\('expiring-task-card'\)\.innerHTML/)
  assert.doesNotMatch(appTaskPages, /byId\('expiring-enable'\)\.checked/)
  assert.doesNotMatch(appTaskPages, /byId\('expiring-cron'\)\.value/)
  assert.doesNotMatch(appTaskPages, /byId\('expiring-backpack-wrap'\)\.innerHTML/)
  assert.doesNotMatch(appTaskPages, /byId\('expiring-table-wrap'\)\.innerHTML/)
  assert.match(appPages, /window\.DOUYU_KEEP_WEBUI_PAGES/)
  assert.match(appPages, /renderOverview/)
  assert.match(appPages, /douyu-keep-webui:overview-page/)
  assert.match(appPages, /douyu-keep-webui:login-page/)
  assert.doesNotMatch(appPages, /byId\('overview-basic-summary'\)\.innerHTML/)
  assert.doesNotMatch(appPages, /byId\('overview-gift-summary'\)\.innerHTML/)
  assert.doesNotMatch(appPages, /byId\('overview-fans-note'\)\.textContent/)
  assert.doesNotMatch(appPages, /byId\('overview-fans-table-wrap'\)\.innerHTML/)
  assert.doesNotMatch(appPages, /buildFansStatusTable\(state\.fansStatus\)/)
  assert.doesNotMatch(appPages, /byId\('logs-summary'\)/)
  assert.doesNotMatch(appPages, /full-log-box/)
  assert.doesNotMatch(appPages, /byId\('cookie-login-card'\)\.innerHTML/)
  assert.doesNotMatch(appPages, /byId\('main-cookie-input'\)\.value/)
  assert.doesNotMatch(appPages, /byId\('cookie-cloud-enable'\)\.checked/)
  assert.match(appResourceActions, /window\.DOUYU_KEEP_WEBUI_RESOURCE_ACTIONS/)
  assert.match(appResourceActions, /DOUYU_KEEP_WEBUI_FANS_RESOURCE_ACTIONS/)
  assert.match(appActions, /window\.DOUYU_KEEP_WEBUI_ACTIONS/)
  assert.match(appActions, /loadProtectedData/)
  assert.doesNotMatch(appActions, /DOUYU_KEEP_WEBUI_AUTH_ACTIONS/)
  assert.doesNotMatch(appActions, /loginWithPassword/)
  assert.doesNotMatch(appActions, /function saveTheme/)
  assert.match(appSimpleTaskActions, /window\.DOUYU_KEEP_WEBUI_SIMPLE_TASK_ACTIONS/)
  assert.match(appSimpleTaskActions, /DOUYU_KEEP_WEBUI_COLLECT_TASK_ACTIONS/)
  assert.match(appSimpleTaskActions, /DOUYU_KEEP_WEBUI_YUBA_TASK_ACTIONS/)
  assert.doesNotMatch(appSimpleTaskActions, /byId\('collect-enable'\)/)
  assert.doesNotMatch(appSimpleTaskActions, /byId\('collect-cron'\)/)
  assert.doesNotMatch(appSimpleTaskActions, /byId\('yuba-enable'\)/)
  assert.doesNotMatch(appSimpleTaskActions, /byId\('yuba-cron'\)/)
  assert.match(appSendTaskActions, /window\.DOUYU_KEEP_WEBUI_SEND_TASK_ACTIONS/)
  assert.match(appSendTaskActions, /DOUYU_KEEP_WEBUI_KEEPALIVE_TASK_ACTIONS/)
  assert.match(appSendTaskActions, /DOUYU_KEEP_WEBUI_DOUBLE_TASK_ACTIONS/)
  assert.match(appSendTaskActions, /DOUYU_KEEP_WEBUI_EXPIRING_TASK_ACTIONS/)
  assert.match(appSendTaskActions, /saveKeepaliveConfig/)
  assert.match(appSendTaskActions, /saveDoubleConfig/)
  assert.match(appSendTaskActions, /saveExpiringGiftConfig/)
  assert.doesNotMatch(appSendTaskActions, /byId\('keepalive-enable'\)/)
  assert.doesNotMatch(appSendTaskActions, /byId\('keepalive-cron'\)/)
  assert.doesNotMatch(appSendTaskActions, /byId\('keepalive-model'\)/)
  assert.doesNotMatch(appSendTaskActions, /byId\('double-enable'\)/)
  assert.doesNotMatch(appSendTaskActions, /byId\('double-cron'\)/)
  assert.doesNotMatch(appSendTaskActions, /byId\('double-model'\)/)
  assert.doesNotMatch(appSendTaskActions, /querySelector\('\.double-value/)
  assert.doesNotMatch(appSendTaskActions, /querySelectorAll\('\.double-enabled/)
  assert.doesNotMatch(appSendTaskActions, /byId\('expiring-enable'\)/)
  assert.doesNotMatch(appSendTaskActions, /byId\('expiring-cron'\)/)
  assert.doesNotMatch(appSendTaskActions, /byId\('expiring-model'\)/)
  assert.doesNotMatch(appSendTaskActions, /querySelector\('\.expiring-value/)
  assert.match(appTaskActions, /window\.DOUYU_KEEP_WEBUI_TASK_ACTIONS/)
  assert.match(appTaskActions, /DOUYU_KEEP_WEBUI_SEND_TASK_ACTIONS/)
  assert.match(appEvents, /window\.DOUYU_KEEP_WEBUI_EVENTS/)
  assert.match(appEvents, /createEventBindings/)
  assert.match(appEvents, /douyu-keep-webui:navigation/)
  assert.match(appEvents, /douyu-keep-webui:refresh-overview-request/)
  assert.doesNotMatch(appEvents, /login-form'\)\.addEventListener/)
  assert.doesNotMatch(appEvents, /action === 'refresh-overview'/)
  assert.doesNotMatch(appEvents, /data-action'\) === 'logout'/)
  assert.doesNotMatch(appEvents, /data-theme-mode/)
  assert.doesNotMatch(appEvents, /refresh-logs/)
  assert.doesNotMatch(appEvents, /clear-logs/)
  assert.doesNotMatch(appEvents, /logs-auto-refresh/)
  assert.doesNotMatch(appEvents, /save-cookie/)
  assert.doesNotMatch(appEvents, /save-cookie-cloud/)
  assert.doesNotMatch(appEvents, /check-cookie-source/)
  assert.doesNotMatch(appEvents, /cookie-cloud-cron/)
  assert.doesNotMatch(appEvents, /cookie-cloud-enable/)
  assert.doesNotMatch(appEvents, /save-collect/)
  assert.doesNotMatch(appEvents, /collect-cron/)
  assert.doesNotMatch(appEvents, /collect-enable/)
  assert.doesNotMatch(appEvents, /save-yuba/)
  assert.doesNotMatch(appEvents, /yuba-cron/)
  assert.doesNotMatch(appEvents, /yuba-enable/)
  assert.doesNotMatch(appEvents, /save-keepalive/)
  assert.doesNotMatch(appEvents, /keepalive-cron/)
  assert.doesNotMatch(appEvents, /keepalive-enable/)
  assert.doesNotMatch(appEvents, /save-double/)
  assert.doesNotMatch(appEvents, /double-cron/)
  assert.doesNotMatch(appEvents, /double-enable/)
  assert.doesNotMatch(appEvents, /double-fill-equal/)
  assert.doesNotMatch(appEvents, /double-fill-level/)
  assert.doesNotMatch(appEvents, /double-value/)
  assert.doesNotMatch(appEvents, /double-enabled/)
  assert.doesNotMatch(appEvents, /save-expiring/)
  assert.doesNotMatch(appEvents, /expiring-cron/)
  assert.doesNotMatch(appEvents, /expiring-threshold-hours/)
  assert.doesNotMatch(appEvents, /expiring-enable/)
  assert.doesNotMatch(appEvents, /saveTheme/)
  assert.doesNotMatch(appActions, /function clearLogs/)
  assert.doesNotMatch(appActions, /method: 'DELETE'/)
  assert.doesNotMatch(appPages, /byId\('theme-note'\)\.textContent/)
  assert.match(styles, /:root\{/)
  assert.match(componentStyles, /\.grid\{/)
  assert.match(tableStyles, /\.table-shell\{/)
  assert.match(responsiveStyles, /@media \(prefers-reduced-motion: reduce\)/)
})
