version: '3.8'

services:
  douyu-keep:
    build: .
    container_name: douyu-keep
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./config:/app/config
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_PATH=/app/config/config.json
      - PUPPETEER_ARGS=--no-sandbox
